name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Start migrations
        run: php artisan migrate
      #- name: Execute tests (Unit and Feature tests) via PHPUnit
        #run: php artisan test

  # *********************     DEPLOY ***************************************
  build:
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Формиурем архив
        run: |
          tar -cvf ${{ secrets.SITE }}.tar ../
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "${{ secrets.SITE }}.tar"
          target: "~/github"
      - name: Удаляем старые файлы из временной директории
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/github/ && rm -Rfv ${{ secrets.SITE }}
      - name: Разархивуруем архив
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/github && tar -xvf ${{ secrets.SITE }}.tar
      - name: Пишем файлы в рабочий каталог
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/github && rsync -avy --delete --exclude 'export' --exclude '.git' --exclude '.github' --exclude '.env' ~/github/empera_wallet/ ~/www/${{ secrets.SITE }}
      - name: Composer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/www/${{ secrets.SITE }} && /opt/php/7.4/bin/php ~/bin/composer install
